name: Linux

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  linux-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Build Release
        run: swift build -c release
