name: Linux

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ["latest"]
    container:
      image: swift:${{ matrix.swift }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install sqlite3
        run: |
          apt-get update
          apt-get install sqlite3 libsqlite3-dev
      - name: pkg-config sqlite3
        run: pkg-config sqlite3 --debug
      - name: Build Debug
        run: swift build -c debug
      - name: Build Release
        run: swift build -c release
